config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users_admin, controller: 'users'

  resources :comptes do 
    get :balance
  end
  
  get 'moncompte/index'
  get 'moncompte/releve_compte'
  get 'moncompte/factures'
  get 'moncompte/absences'
  get 'moncompte/enfants'
  get 'moncompte/reservations'
  get 'moncompte/contacts'

  resources :factures do
    collection do
      post :action
    end
  end

  resources :enfants do
    collection do
      post :action
      post :action_execute
    end
  end

  resources :reservations, except: %i[ show create update ] do
    collection do
      post :action
      post :create_visiteur
    end
  end

  resources :prestations do
    collection do
      post :action
    end
  end
  resources :tarifs
  resources :absences
  resources :tarif_types, except: %i[ index show ]
  resources :prestation_types, except: %i[ index show ]
  resources :structures, except: %i[ index new create ]
  resources :organisations do
    member do
      get :suppression_organisation
      post :suppression_organisation_do
    end
  end
  resources :paiements
  resources :facture_messages
  resources :messages do
    member do
      get :traiter
      get :archiver
    end
  end
  resources :vacances
  resources :mail_logs, only: %i[ index show ]
  resources :pointages, only: %i[ index edit update ] do
    collection do
      post :action
    end
  end

  namespace :admin do
    get :index
    get :ajout_prestations
    get :ajout_factures
    get :tarifs
    get :audit
    get :import
    get :exemple_fichier_import_xls
    get :envoyer_factures
    get :mode_demonstration

    post :ajout_prestations_do
    post :ajout_factures_do
    post :import_do
    post :envoyer_factures_do
  end

  controller :pages do
    get :accueil, to: 'pages#home'
    get :guide, to: 'pages#guide'
    get :actualites, to: 'pages#actualites'
    get :confidentialite, to: 'pages#confidentialite'
    post :conditions_generales_de_vente, to: 'pages#conditions_generales_de_vente'
    get :dashboard, to: 'pages#dashboard'
  end

  root 'pages#accueil'

end

app/models/compte.rb
class Compte < ApplicationRecord
  extend FriendlyId
  friendly_id :nom, use: :slugged

  audited

  belongs_to :organisation 

  validates :nom, presence: true

  has_many :contacts, inverse_of: :compte, dependent: :delete_all
  has_many :enfants, dependent: :delete_all
  has_many :factures
  has_many :paiements

  has_many :prestations, through: :enfants
  has_many :reservations, through: :enfants
  has_many :absences, through: :enfants

  accepts_nested_attributes_for :contacts, reject_if: proc { |attributes| attributes[:nom].blank? }, allow_destroy: true

  default_scope { order(Arel.sql('comptes.nom')) }

  # self.per_page = 10

  def balance
    solde = 0.00 
    debit = 0.00 
    credit = 0.00
    releve = []

    self.factures.each do |f|
      releve << { id: f.id, date: f.date.to_date, type: "Facture", ref: f.réf, mnt: f.montant, solde: 0 }
    end

    self.paiements.each do |p|
      releve << { id: p.id, date: p.date.to_date, type: "Paiement", ref: "#{p.mode} #{p.banque} #{p.chèque_num}", mnt: p.montant, solde: 0 }
    end

    releve = releve.sort_by { |r| r[:date] }

    releve.each do |r|
      mnt = r[:mnt]
      if r[:type] == "Facture"
        debit += mnt
        solde -= mnt
      else
        credit += mnt
        solde += mnt
      end
      r[:solde] = solde
    end 
  end

  def solde_avant_cette_facture(facture)
    self.paiements.sum(:montant) - (self.factures.sum(:montant) - facture.montant)
  end

  def solde
    self.paiements.sum(:montant) - self.factures.sum(:montant)
  end

  def self.xls_headers
    %w{organisation nom_compte civilité adresse1 adresse2 cp ville num_allocataire mémo_compte
      nom_enfant prénom classe référent date_naissance menu_sp menu_all tarif_type badge allergenes mémo_enfant
      nom_contact1 fixe1 portable1 email1 prevenir1 mémo_contact1
      nom_contact2 fixe2 portable2 email2 prevenir2 mémo_contact2
      nom_contact3 fixe3 portable3 email3 prevenir3 mémo_contact3 }  
  end

  def nom_civilité
    "#{self.civilité} #{self.nom}"
  end

end

app/controllers/comptes_controller.rb
class ComptesController < ApplicationController
  before_action :set_compte, only: [:show, :balance, :edit, :update, :destroy]
  before_action :calcul_solde_balance, only: [:show, :balance]

  helper_method :sort_column, :sort_direction

  # GET /comptes
  # GET /comptes.json
  def index
    authorize Compte

    @structures = current_user.organisation.structures

    if current_user.visiteur?
      @comptes = Compte.where(id: Contact.find_by(email: current_user.email).compte_id)
    else
      @comptes = current_user.organisation.comptes
    end
    
    unless params[:search].blank?
      s = "%#{params[:search].upcase}%"
      @comptes = @comptes.joins(:enfants).where('enfants.badge ILIKE :search OR enfants.prénom ILIKE :search OR comptes.nom ILIKE :search OR comptes.cp ILIKE :search OR comptes.ville ILIKE :search OR comptes.num_allocataire ILIKE :search', {search: s})
    end

    # Appliquer le tri
    @comptes = @comptes.reorder(Arel.sql("#{sort_column} #{sort_direction}"))
    
    respond_to do |format|
      format.html do 
        @comptes = @comptes.page(params[:page])
      end

      format.xls do
        book = ComptesToXls.new(@comptes).call
        file_contents = StringIO.new
        book.write file_contents # => Now file_contents contains the rendered file output
        filename = "Comptes.xls"
        send_data file_contents.string.force_encoding('binary'), filename: filename 
      end
    end
  end

  # GET /comptes/1
  # GET /comptes/1.json
  def show
    authorize @compte
  end

  def balance
    authorize (Compte)

    @releve = @compte.balance
  end

  # GET /comptes/new
  def new
    authorize Compte
    
    @compte = Compte.new
    @compte.organisation = current_user.organisation
    
    1.times { @compte.contacts.build }
  end

  # GET /comptes/1/edit
  def edit
    authorize Compte
    
    @structures = current_user.organisation.structures
  end

  # POST /comptes
  # POST /comptes.json
  def create
    authorize Compte
    
    @compte = Compte.new(compte_params)

    respond_to do |format|
      if @compte.save
        create_contacts
        format.html { redirect_to @compte, notice: 'Compte créé avec succès.' }
        format.json { render :show, status: :created, location: @compte }
      else
        format.html { render :new }
        format.json { render json: @compte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comptes/1
  # PATCH/PUT /comptes/1.json
  def update
    authorize Compte

    respond_to do |format|
      if @compte.update(compte_params)
        create_contacts
        format.html { redirect_to @compte, notice: 'Compte modifié avec succès.' }
        format.json { render :show, status: :ok, location: @compte }
      else
        format.html { render :edit }
        format.json { render json: @compte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comptes/1
  # DELETE /comptes/1.json
  def destroy
    authorize Compte

    begin
      @compte.destroy
    rescue ActiveRecord::InvalidForeignKey
      redirect_to comptes_url, alert: "Le compte ne peut pas être supprimé pour le moment car des éléments liés existent. Veuillez d'abord supprimer ces éléments liés (Enfants/Factures...) avant de retenter l'opération."
      return
    end
    
    respond_to do |format|
      format.html { redirect_to comptes_url, notice: 'Compte supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compte
      @compte = Compte.friendly.find(params[:id].present? ? params[:id] : params[:compte_id])
    end

    def calcul_solde_balance
      @total_factures  = @compte.factures.sum(:montant)
      @total_paiements = @compte.paiements.sum(:montant)
      @solde = @total_paiements - @total_factures
    end

    def create_contacts
      if params[:acces] == "1"
        @compte.contacts.each do |contact|
          if contact.prevenir && User.find_by(email: contact.email).nil?
            password = SecureRandom.hex(10)
            user = User.create(organisation: current_user.organisation, role: "visiteur", email: contact.email, password: password, confirmed_at: DateTime.now)
            UserMailer.with(user: user, password: password, organisation: current_user.organisation).welcome_with_password.deliver_now
            UserMailer.with(user: user).new_account_notification.deliver_now
          end
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compte_params
      params.require(:compte).permit(:organisation_id, :nom, :civilité, :adresse1, :adresse2, :cp, :ville, :num_allocataire, :mémo,
                                      contacts_attributes: [:id, :nom, :fixe, :portable, :email, :mémo, :prevenir, :_destroy])
    end

    def sortable_columns
      %w{structures.nom comptes.nom comptes.civilité comptes.adresse1 comptes.cp comptes.ville comptes.num_allocataire comptes.enfants_count}
    end
  
    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : 'id'
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end

end

app/views/comptes/_balance.html.erb
<tr>
    <td><%= l ligne[:date] %></td>
    <td><%= ligne[:type] %></td>
    <% if ligne[:type] == "Facture" %>
        <td><%= link_to ligne[:ref], facture_url(Facture.find(ligne[:id]), format: :pdf) %></td>
        <td class="text-end"><%= number_to_currency(ligne[:mnt], unit:'€') %></td>
        <td></td>
    <% else %>
        <td><%= ligne[:ref] %></td>
        <td></td>
        <td class="text-end"><%= number_to_currency(ligne[:mnt], unit:'€') %></td>
    <% end %>
    <td class="text-end"><%= number_to_currency(ligne[:solde], unit:'€') %></td>
</tr>

app/views/comptes/_compte-card.html.erb
<div class="row">
  <div class="col-sm-5">
    <p>
      <strong>Nom :</strong>
      <%= @compte.civilité %>
      <%= @compte.nom %>
    </p>

    <p>
      <strong>Adresse :</strong>
      <%= @compte.adresse1 %>
      <%= @compte.adresse2 %>
    </p>

    <p>
      <strong>Ville :</strong>
      <%= @compte.cp %> <%= @compte.ville %>
    </p>

    <% unless current_user.visiteur? %>
      <p>
        <strong>#Allocataire :</strong>
        <%= @compte.num_allocataire %>
      </p>

      <p>
        <strong>Mémo :</strong>
        <%= @compte.mémo %>
      </p>
    <% end %>
    
    <% if policy(@compte).edit? %>
      <%= link_to edit_compte_path(@compte), class: "btn btn-outline-primary" do %>
        <%= fa_icon 'edit', text: ' Éditer compte' %>
      <% end %>
    <% end %>

  </div>

  <div class="col">

    <div class="card">
      <div class="card-body">
        <strong>Contacts</strong>
        <table class="table table-hover table-borderless table-sm">
          <% @compte.contacts.each do |contact| %>
            <tr class="alert <%= 'alert-warning' if contact.prevenir? %>" >
              <td><%= contact.nom.humanize %></td>
              <td><%= mail_to contact.email, class:"text-break" %>
              <td><%= [contact.fixe, contact.portable].join(' ') %>
              <td><%= contact.mémo %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="card">
      <div class="card-body d-flex justify-content-between">
        <div>
          <strong>Factures : </strong>
          <%= number_to_currency(@total_factures, unit: '€', precision: 2, format: "%n %u")  %>
        </div>
        |
        <div>
          <strong>Paiements : </strong>
          <%= number_to_currency(@total_paiements, unit: '€', precision: 2, format: "%n %u")  %>
        </div>
        | 
        <div>
          <strong>Solde : </strong>
          <span class="<%= 'text-danger' if @solde.negative? %>">
            <%= number_to_currency(@solde, unit: '€', precision: 2, format: "%n %u") %>
          </span>
        </div>
      </div>

      <% unless current_user.visiteur? %>
        <div class="card-footer d-flex justify-content-between">
          <% if policy(Facture).new? %>
            <div>
              <%= link_to admin_ajout_factures_path(compte_id: @compte.id), class: "btn btn-sm", title: 'Lance la facturation des prestations du mois' do %>
                <%= fa_icon 'file-invoice', class: 'text-info me-1' %> Facturer
              <% end %>
            </div>
          <% end %>
          |
          <% if policy(Facture).new? %>
            <div>
              <%= link_to new_facture_path(compte_id: @compte.id), class: "btn btn-sm", title: 'Créer une nouvelle facture manuelle' do %>
                <%= fa_icon 'file-invoice', class: 'text-info me-1' %> Nouvelle facture spéciale
              <% end %>
            </div>
          <% end %>
          |
          <% if policy(Paiement).new? %>
            <div>
              <%= link_to new_paiement_path(compte_id: @compte.id), data: {'bs-toggle': "modal", 'bs-target': "#myModalNewPaiement" }, class: "btn btn-sm" do %>
                <i class="far fa-money-bill-alt text-success me-1"></i> Ajouter un paiement
              <% end %>
            </div>
          <% end %>
          | 
          <% if policy(@compte).balance? %>
            <div>
              <%= link_to compte_balance_path(@compte), class: "btn btn-sm" do %>
                <%= fa_icon 'balance-scale', class: 'me-1' %> Balance
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/comptes/_compte.html.erb
<tr>
    <td><%= link_to compte.nom, compte %></td>
    <td><%= compte.enfants.pluck(:prénom).join(', ') %> (<%= compte.enfants_count %>)</td>
    <td><%= compte.adresse1 %></td>
    <td><%= compte.cp %></td>
    <td><%= compte.ville %></td>
    <td class="text-end"><%= number_to_currency compte.solde %></td>
    <td><% if policy(compte).edit? %>
            <%= link_to edit_compte_path(compte), class:'btn btn-link btn-sm' do %>
                <%= fa_icon 'edit' %>
            <% end %>
        <% end %>
    </td>
    <td>
        <% if policy(compte).destroy? %>
            <%= button_to compte, method: :delete, 'data-turbo-confirm': 'Attention ! Les enfants liés à ce compte seront effacés ! Êtes-vous bien certain.e ???', class: 'btn btn-sm' do %>
                <%= fa_icon 'trash-alt', class: 'text-danger' %>
            <% end %>
        <% end %>
    </td>
</tr>

app/views/comptes/_contact_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="row">
      <div class="col"><%= f.text_field :nom, label_as_placeholder: true, required: true %></div>
      <div class="col"><%= f.email_field :email, label_as_placeholder: true, required: true %></div>
  </div>
  <div class="row">
    <div class="col"><%= f.text_field :fixe, label_as_placeholder: true %></div>
    <div class="col"><%= f.text_field :portable, label_as_placeholder: true %></div>
    <div class="col"><%= f.check_box :prevenir, label_as_placeholder: true, label: "Personne à prévenir en cas d'urgence" %></div>
    <div class="col-1"><a type="button" data-action="nested-form#remove"><%= fa_icon 'trash-alt', class:"text-danger mt-3" %></a></div>
  </div>
  <hr>
  <%= f.hidden_field :_destroy %>
</div>

app/views/comptes/_form.html.erb
<%= bootstrap_form_with(model: compte, local: true, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }) do |form| %>

  <%= form.hidden_field :organisation_id %>

  <div class="row">
    <div class="col-sm-6 mb-3">
      <div class="row">
        <div class="col-sm-9">
          <%= form.text_field :nom, required: true, autofocus: false, label: "Nom *" %>
        </div>
        <div class="col-sm-3">
          <%= form.select :civilité, ["M et Mme","Mme", "M"] %>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <%= form.text_field :adresse1, label: "Adresse" %>
        </div>
        <div class="col">
          <%= form.text_field :adresse2, label: "Adresse complémentaire" %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3"><%= form.text_field :cp %></div>
        <div class="col-sm-9"><%= form.text_field :ville %></div>
      </div>
      <%= form.text_field :num_allocataire, label: "Numéro d'Allocataire" %>
      <%= form.text_area :mémo %>
      <%= check_box_tag :acces %>
      <%= label_tag :acces, "Créer automatiquement un compte d'accès au portail parents pour les contacts à prévenir en cas d'urgence et leur envoyer une notification ?", class:'d-inline' %>
    </div>

    <div class="col-sm-6">
      <h5>
        Contacts
      </h5>
      <template data-nested-form-target="template">
        <%= form.fields_for :contacts, Contact.new, child_index: 'NEW_RECORD' do |contact_fields| %>
          <%= render "contact_form", f: contact_fields %>
        <% end %>
      </template>

      <%= form.fields_for :contacts do |contact_fields| %>
        <%= render "contact_form", f: contact_fields %>
      <% end %>

      <!-- Inserted elements will be injected before that target. -->
      <div data-nested-form-target="target"></div>

      <button class="btn btn-outline-primary" type="button" data-action="nested-form#add"><%= fa_icon 'plus-circle' %> Ajouter un contact</button>
    </div>
  </div>

  <p>* : Champs requis</p>

  <div class="mb-3">
    <%= form.submit "Enregistrer", class: "btn btn-outline-success" %>
  </div>

<% end %>

app/views/comptes/balance.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2><%= fa_icon 'balance-scale' %> Balance</h2>
</div>

<p>
	<h3>Compte: <%= @compte.nom %></h3> 
	Solde à ce jour: <%= number_to_currency(@solde, unit:'€') %>
</p>

<table class="table table-hover table-bordered table-striped">

	<thead>
		<th>Date</th>
		<th>Type</th>
		<th>Référence</th>
		<th class="text-end">Débit</th>
		<th class="text-end">Crédit</th>
		<th class="text-end">Solde</th>
	</thead>

	<tbody>
		<% @releve.each do |ligne| %>
			<%= render partial: 'balance', locals: { ligne: ligne } %>
		<% end %>
    </tbody>

	<tfoot>
		<tr>
			<th><%= l Date.today %></th>
			<th>SOLDE</th>
			<th></th>
			<th class="text-end"><%= number_to_currency(@debit, unit:'€') %></th>
			<th class="text-end"><%= number_to_currency(@credit, unit:'€') %></th>
			<th class="text-end"><%= number_to_currency(@solde, unit:'€') %></th>
		</tr>
	</tfoot>
	
</table>

app/views/comptes/edit.html.erb
<h2><%= fa_icon 'child', class: 'text-primary' %> Éditer Compte</h2>

<%= render 'form', compte: @compte %>

<%= link_to 'Voir', @compte %> |
<%= link_to 'Retour', comptes_path %>

app/views/comptes/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <% if policy(Compte).new? %>
    <%= link_to new_compte_path, class: 'btn btn-outline-primary float-end' do %>
      <%= fa_icon 'plus-circle' %> Ajouter un Compte
    <% end %>
  <% end %>
  <h2 class="fw-light d-inline"><%= fa_icon 'users' %> Comptes</h2>
  <%= link_to guide_path(anchor: "ajout_famille") do %>
    <%= fa_icon 'question-circle', type: :regular, title: "Ouvrir l'aide", class: 'text-muted mx-2' %>
  <% end %>
</div>

<%= bootstrap_form_tag url: comptes_path, method: :get do |f| %>
  <div class="row">
    <div class="col">
      <%= f.text_field :search, 
                        value: params[:search], 
                        label: 'Rechercher',
                        placeholder: 'Entrez un terme à rechercher (ex: Nom, Prénom enfant, Code postal, Ville, Numéro allocataire, Badge)', 
                        onchange: 'this.form.submit()', 
                        autofocus: false %>
    </div>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link 'comptes.nom', 'Nom' %></th>
        <th><%= sort_link 'comptes.enfants_count', 'Enfants' %></th>
        <th><%= sort_link 'comptes.adresse1', 'Adresse' %></th>
        <th><%= sort_link 'comptes.cp', 'CP'%></th>
        <th><%= sort_link 'comptes.ville', 'Ville' %></th>
        <td class="sortlink-style">Solde</td>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @comptes %>
    </tbody>

  </table>
</div>

<%= page_entries_info @comptes, entry_name: 'compte' %>
<%= paginate @comptes, theme: 'twitter-bootstrap-4' %>

<% if policy(Compte).to_xls? && !@comptes.size.zero? %>
  <%= link_to url_for(params.permit(:search).merge(format: :xls)),
              class: "float-sm-end text-success" do %>
      <%= fa_icon "file-excel", class: 'me-1 mb-5', text: "Export XLS" %>
  <% end %>
<% end %>

app/views/comptes/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2><%= fa_icon 'users' %> Nouveau Compte</h2>
</div>
<br>

<%= render 'form', compte: @compte %>
<br>

app/views/comptes/show.html.erb
<div class="card my-3">
  <div class="card-header">
    <h2><%= fa_icon 'user' %> <%= @compte.nom %></h2>
  </div>

  <div class="card-body">
    <%= render partial: "compte-card" %>
    <div class="card mt-3">
      <div class="card-body">

        <h4><%= fa_icon 'child', class: 'text-primary' %> Enfants</h4>
        <table class="table table-hover table-sm">
          <thead>
            <tr>
              <th>Nom</th>
              <th>Prénom</th>
              <th>Date naissance</th>
              <th>Classe</th>
              <th>ALLERGIE?</th>
              <th>Menu SP?</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <% @compte.enfants.each do |enfant| %>
            <tr>
              <td><%= enfant.nom %></td>
              <td><%= link_to enfant.prénom, enfant %></td>
              <td><%= l(enfant.date_naissance) if enfant.date_naissance %></td>
              <td><%= enfant.classroom.nom %></td>
              <td class="text-center"><%= fa_icon('exclamation', title: enfant.allergenes) if enfant.menu_all %></td>
              <td class="text-center"><%= fa_icon 'exclamation' if enfant.menu_sp %></td>
              <td>
                <% if policy(enfant).edit? %>
                  <%= link_to edit_enfant_path(enfant), class: 'btn btn-link btn-sm' do %>
                    <%= fa_icon 'edit' %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if policy(enfant).destroy? %>
                  <%= button_to enfant, method: :delete, 'data-turbo-confirm': 'Êtes-vous bien certain.e ???', class: 'btn btn-sm' do %>
                      <%= fa_icon 'trash-alt', class: 'text-danger' %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>

        </table>

        <% if policy(Enfant).new? %>
          <%= link_to new_enfant_path(compte_id: @compte), class: "btn btn-outline-primary" do %>
            <%= fa_icon 'plus-circle' %> Ajouter un enfant
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalNewPaiement">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Nouveau Paiement</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <%= render 'paiements/form', paiement: Paiement.new(compte_id: @compte.id, date: Date.today, réf: current_user.organisation.factures.where(compte_id: @compte.id, workflow_state: "vérifiée").last.try(:réf)) %>
      </div>
    </div>
  </div>
</div>