config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users_admin, controller: 'users'

  resources :comptes do 
    get :balance
  end
  
  get 'moncompte/index'
  get 'moncompte/releve_compte'
  get 'moncompte/factures'
  get 'moncompte/absences'
  get 'moncompte/enfants'
  get 'moncompte/reservations'
  get 'moncompte/contacts'

  resources :factures do
    collection do
      post :action
    end
  end

  resources :enfants do
    collection do
      post :action
      post :action_execute
    end
  end

  resources :reservations, except: %i[ show create update ] do
    collection do
      post :action
      post :create_visiteur
    end
  end

  resources :prestations do
    collection do
      post :action
    end
  end
  resources :tarifs
  resources :absences
  resources :tarif_types, except: %i[ index show ]
  resources :prestation_types, except: %i[ index show ]
  resources :structures, except: %i[ index new create ]
  resources :organisations do
    member do
      get :suppression_organisation
      post :suppression_organisation_do
    end
  end
  resources :paiements
  resources :facture_messages
  resources :messages do
    member do
      get :traiter
      get :archiver
    end
  end
  resources :vacances
  resources :mail_logs, only: %i[ index show ]
  resources :pointages, only: %i[ index edit update ] do
    collection do
      post :action
    end
  end

  namespace :admin do
    get :index
    get :ajout_prestations
    get :ajout_factures
    get :tarifs
    get :audit
    get :import
    get :exemple_fichier_import_xls
    get :envoyer_factures
    get :mode_demonstration

    post :ajout_prestations_do
    post :ajout_factures_do
    post :import_do
    post :envoyer_factures_do
  end

  controller :pages do
    get :accueil, to: 'pages#home'
    get :guide, to: 'pages#guide'
    get :actualites, to: 'pages#actualites'
    get :confidentialite, to: 'pages#confidentialite'
    post :conditions_generales_de_vente, to: 'pages#conditions_generales_de_vente'
    get :dashboard, to: 'pages#dashboard'
  end

  root 'pages#accueil'

end

app/models/enfant.rb
class Enfant < ApplicationRecord
  extend FriendlyId
  friendly_id :nom_et_prénom, use: :slugged

  audited
  
  belongs_to :compte, counter_cache: true
  belongs_to :classroom
  belongs_to :tarif_type

  has_one :organisation, through: :compte

  has_many :reservations, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :prestations, dependent: :destroy
  has_many :pointages

  accepts_nested_attributes_for :reservations, reject_if: proc { |attributes| attributes[:prestation_type_id].blank? }, allow_destroy: true

  validates :compte_id, :classroom_id, :tarif_type_id, :nom, :prénom, presence: true

  default_scope { order(Arel.sql('enfants.nom, enfants.prénom')) }

  # self.per_page = 10

  def nom_et_prénom
    "#{self.nom} #{self.prénom}"
  end

  def prénom_et_nom
    "#{self.prénom} #{self.nom}"
  end

end

app/controllers/enfants_controller.rb
class EnfantsController < ApplicationController
  before_action :set_enfant, only: [:show, :edit, :update, :destroy]
  before_action :populate_select, only: [:new, :edit]
  
  helper_method :sort_column, :sort_direction

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_child

  # GET /enfants
  # GET /enfants.json
  def index
    authorize Enfant

    organisation = current_user.organisation
    @enfants = organisation.enfants
    @structures = organisation.structures
    @classrooms = organisation.classrooms

    unless params[:structure_id].blank?
      @enfants = @enfants.joins(:classroom).where(classrooms: { structure_id: params[:structure_id] })
      @classrooms = @classrooms.where(structure_id: params[:structure_id])      
    end

    unless params[:classroom_id].blank?
      @enfants = @enfants.where(classroom_id: params[:classroom_id])      
    end
    
    unless params[:search].blank?
      s = "%#{params[:search].upcase}%"
      @enfants = @enfants.where('enfants.nom ILIKE :search OR enfants.prénom ILIKE :search OR enfants.badge ILIKE :search', {search: s})
    end

    # Appliquer le tri
    @enfants = @enfants.joins(:compte).reorder(Arel.sql("#{sort_column} #{sort_direction}"))

    respond_to do |format|
      format.html do 
        @enfants = @enfants.page(params[:page])
      end
      format.xls do
        book = ComptesToXls.new(Compte.where(id: @enfants.pluck(:compte_id))).call
        file_contents = StringIO.new
        book.write file_contents # => Now file_contents contains the rendered file output
        filename = "Enfants.xls"
        send_data file_contents.string.force_encoding('binary'), filename: filename 
      end
    end
  end

  def action
    return unless params[:enfants_id]
    enfants = Enfant.where(id: params[:enfants_id].keys)

    case params[:action_name]
    when "Marquer comme absent ce jour"
      enfants = enfants.each do | enfant | 
        enfant.absences.create(début: Date.today, fin: Date.today)
      end
      flash[:notice] = "#{enfants.count} absence.s créée.s" 
      redirect_to enfants_url
    when "Changer de classe"
    end

  end

  def action_execute
    return unless params[:enfants_id]
    enfants = Enfant.where(id: params[:enfants_id].split(' '))

    enfants = enfants.each do | enfant | 
      enfant.classroom_id = params[:classroom_id]
      enfant.save
    end
    flash[:notice] = "#{enfants.count} enfants déplacé.e.s" 
    redirect_to enfants_url
  end

  # GET /enfants/1
  # GET /enfants/1.json
  def show
    authorize @enfant
    if params[:archives] == 'yes'
      @absences = @enfant.absences.unscoped
    else
      @absences = @enfant.absences
    end
  end

  # GET /enfants/new
  def new
    authorize Enfant

    @enfant = Enfant.new
    @enfant.compte = Compte.friendly.find(params[:compte_id]) 
    
    # Valeurs par défaut de la réservation

    @enfant.reservations
              .build(début: @enfant.organisation.vacances_été.fin , 
                    fin: @enfant.organisation.vacances_été.début + 1.year, 
                    lundi: 1, mardi: 1, mercredi: 1, jeudi: 1, vendredi: 1, midi: true, 
                    workflow_state: 'validée')
  end

  # GET /enfants/1/edit
  def edit
    authorize @enfant
  end

  # POST /enfants
  # POST /enfants.json
  def create
    authorize Enfant

    @enfant = Enfant.new(enfant_params)
    respond_to do |format|
      if @enfant.save
        format.html { redirect_to @enfant, notice: 'Enfant créé avec succès.' }
        format.json { render :show, status: :created, location: @enfant }
      else
        format.html { render :new }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enfants/1
  # PATCH/PUT /enfants/1.json
  def update
    authorize @enfant

    respond_to do |format|
      if @enfant.update(enfant_params)
        format.html { redirect_to @enfant, notice: 'Enfant modifié avec succès.' }
        format.json { render :show, status: :ok, location: @enfant }
      else
        format.html { render :edit }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enfants/1
  # DELETE /enfants/1.json
  def destroy
    authorize @enfant

    begin
      @enfant.destroy
    rescue ActiveRecord::InvalidForeignKey => exception
      #redirect_to enfants_url, alert: "L'enfant ne peut pas être supprimé pour le moment car des éléments liés existent. Veuillez d'abord supprimer ces éléments liés (Réservations/Absences...) avant de retenter l'opération."
      redirect_to enfants_url, alert: exception
      return
    end

    respond_to do |format|
      format.html { redirect_to enfants_url, notice: 'Enfant supprimé avec succès.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enfant
      @enfant = Enfant.friendly.find(params[:id])
    end

    def populate_select
      @classrooms = current_user.organisation.classrooms
      @tarif_types = current_user.organisation.tarif_types
      @prestation_types = current_user.organisation.prestation_types
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enfant_params
      params.require(:enfant)
            .permit(:compte_id, :classroom_id, :nom, :prénom, :date_naissance, :menu_sp, :menu_all, :allergenes, :tarif_type_id, :badge, :mémo,
                    reservations_attributes: [:id, :enfant_id, :prestation_type_id, :workflow_state,
                                              :début, :fin, 
                                              :lundi, :mardi, :mercredi, :jeudi, :vendredi, :samedi, :dimanche,
                                              :matin, :midi, :soir, :hors_période_scolaire, :_destroy])
    end

    def sortable_columns
      %w{structures.nom comptes.nom classrooms.nom comptes.nom enfants.nom enfants.prénom enfants.date_naissance enfants.menu_sp enfants.menu_all}
    end
  
    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : 'enfants.id'
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end

    def invalid_child
      redirect_to enfants_url
    end

end

app/views/enfants/_enfant.html.erb
<tr>
    <td>
        <span data-action="click->action#click">
            <%= check_box_tag "[enfants_id][#{enfant.id}]", 'yes', false,  data: {"action-target":"source"} %>
        </span>
    </td>
    <td><%= enfant.classroom.structure.nom %></td>
    <td><%= enfant.classroom.nom %></td>
    <td><%= link_to enfant.compte.nom, enfant.compte %></td>
    <td><%= enfant.nom %></td>
    <td><%= link_to enfant.prénom, enfant %></td>
    <td><%= l(enfant.date_naissance) if enfant.date_naissance %></td>
    <td class="text-center"><%= fa_icon 'exclamation' if enfant.menu_all %> <%= enfant.allergenes %></td>
    <td class="text-center"><%= fa_icon 'exclamation' if enfant.menu_sp %></td>
    <td><%= truncate(enfant.mémo, length: 10) %></td>
    <td><%= enfant.reservations.actives.joins(:prestation_type).pluck("prestation_types.nom").join(', ') %></td>
    <td>
        <% if policy(enfant).edit? %>
            <%= link_to edit_enfant_path(enfant), class: 'btn btn-link btn-sm' do %>
                <%= fa_icon 'edit' %>
            <% end %>
        <% end %>
    </td>
</tr>

app/views/enfants/_form.html.erb
<%= bootstrap_form_with(model: enfant, local: true, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }) do |f| %>

  <%= f.hidden_field :compte_id %>
  
  <div class="row">
    <div class="col"><%= f.select :classroom_id, options_from_collection_for_select(@classrooms, 'id', 'nom_et_structure', enfant.classroom_id), { label: "Classe" }, { class: "selectpicker" } %></div>
    <div class="col"><%= f.text_field :nom, required: true %></div>
    <div class="col"><%= f.text_field :prénom, required: true %></div>
    <div class="col"><%= f.date_field :date_naissance%></div>
    <div class="col"><%= f.select :tarif_type_id, options_from_collection_for_select(@tarif_types, 'id', 'nom', enfant.tarif_type_id), { label: "Tarif"}, { class: "selectpicker" } %></div>
    <div class="col-sm-1"><%= f.text_field :badge %></div>
  </div>

  <div class="row">
    <div class="col-sm-1">
      <%= f.check_box :menu_all, label: "Allergie", custom: :switch %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :allergenes, label_as_placeholder: true, label: 'Allergènes' %>
    </div>
    <div class="col-sm-2">
      <%= f.check_box :menu_sp, label: "Menu 'Sans porc'", custom: :switch %>
    </div>
    <div class="col">
      <div class="col"><%= f.text_field :mémo, label_as_placeholder: true, label: 'Mémo' %></div>
    </div>
  </div>
  <br>

  <h3><%= fa_icon 'calendar-alt', class: 'text-warning' %> Réservations</h3>
  <hr />
  
  <template data-nested-form-target="template">
    <%= f.fields_for :reservations, Reservation.new, child_index: 'NEW_RECORD' do |reservation_fields| %>
      <%= render "reservation_form", f: reservation_fields %>
    <% end %>
  </template>

  <%= f.fields_for :reservations do |reservation_fields| %>
    <%= render "reservation_form", f: reservation_fields %>
  <% end %>

  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="target"></div>

  <button class="btn btn-outline-primary" type="button" data-action="nested-form#add"><%= fa_icon 'plus-circle' %> Ajouter réservation</button>

  <%= f.submit "Enregistrer", class: "btn btn-outline-success" %>

<% end %>
<br>

app/views/enfants/action.html.erb
<h2 class="mb-4">Changer de classe</h2>
<h3 class="mb-5 fw-lighter">Choisissez la classe de destination</h3>

<div class="row">
  <div class="col-sm-4">
    <%= bootstrap_form_tag url: action_execute_enfants_path, method: :post do %>
      <%= hidden_field_tag :enfants_id, params[:enfants_id].keys %>
      <%= select_tag :classroom_id,
                        options_from_collection_for_select(
                          current_user.organisation.classrooms,
                          'id',
                          'nom_et_structure',
                          params[:classroom_id]
                        ),
                      class: "form-control mb-3"
      %>
      <%=  submit_tag 'Changer', class: 'btn btn-outline-success' %>
      <%= link_to 'Annuler', enfants_path, class: 'btn btn-link'%>
    <% end %>
  </div>
</div>

app/views/enfants/edit.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2><%= fa_icon 'child', class: 'text-primary' %> 
    <%= @enfant.prénom_et_nom %>
  </h2>
</div>
<br>


<%= render 'form', enfant: @enfant %>

<%= link_to 'Voir', @enfant %> |
<%= link_to 'Retour', enfants_path %>

app/views/enfants/index.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2 class="fw-light d-inline"><%= fa_icon 'child', class: 'text-primary' %> Enfants</h2>
  <%= link_to guide_path(anchor: "ajout_enfant") do %>
    <%= fa_icon 'question-circle', type: :regular, title: "Ouvrir l'aide", class: 'text-muted mx-2' %>
  <% end %>
</div>

<%= bootstrap_form_tag url: enfants_path, method: :get do |f| %>
  <div class="row">
    <div class="col"><%= f.text_field :search, value: params[:search], label: 'Nom/Prénom/Badge', onchange: "this.form.submit()", autofocus: false %></div>
    <div class="col-sm-3"><%= f.select :structure_id, options_from_collection_for_select(@structures, 'id', 'nom', params[:structure_id]), { include_blank: true, label: "Structure" }, { class: "selectpicker", onchange: "this.form.submit()" } %></div>
    <div class="col-sm-2"><%= f.select :classroom_id, options_from_collection_for_select(@classrooms, 'id', 'nom', params[:classroom_id]), { include_blank: true, label: "Classe" }, { class: "selectpicker", onchange: "this.form.submit()" } %></div>
  </div>
<% end %>

<%= bootstrap_form_tag url: action_enfants_path, method: :post do %>
  <div class="table-responsive" data-controller="action">
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th><%= sort_link 'structures.nom', 'Structure' %></th>
          <th><%= sort_link 'classrooms.nom', 'Classe' %></th>
          <th><%= sort_link 'comptes.nom', 'Compte' %></th>
          <th><%= sort_link 'enfants.nom', 'Nom' %></th>
          <th><%= sort_link 'enfants.prénom', 'Prénom' %></th>
          <th><%= sort_link 'enfants.date_naissance', 'Né(e) le' %></th>
          <th><%= sort_link 'enfants.menu_all', 'ALLERGIE?' %></th>
          <th><%= sort_link 'enfants.menu_sp', 'SP?' %></th>
          <th><%= sort_link 'enfants.mémo', 'Mémo' %></th>
          <th class="sortlink-style">Réservations</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= render @enfants.includes(:compte, :classroom) %>
      </tbody>
    </table>

    <div class="row">
      <div class="col-sm-4">
        <div class="input-group">
          <%= select_tag :action_name, 
                          options_for_select(["Marquer comme absent ce jour", "Changer de classe"]), 
                          include_blank: true, 
                          class: 'form-control form-control-sm',
                          data: { 'action-target': 'selector' } %>
          <div class="input-group-append">
            <%= submit_tag 'ok',  name: 'action', 
                                  class: 'btn btn-sm btn-outline-success',
                                  data: {'action-target': 'button'} %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= page_entries_info @enfants, entry_name: 'enfant' %>
<%= paginate @enfants, theme: 'twitter-bootstrap-4' %>

<% if policy(Enfant).to_xls? && !@enfants.size.zero? %>
  <%= link_to url_for(params.permit(:search).merge(format: :xls)),
              class: "float-sm-end text-success" do %>
      <%= fa_icon "file-excel", class: 'me-1 mb-5', text: "Export XLS" %>
  <% end %>
<% end %>

app/views/enfants/new.html.erb
<div class="pb-2 mt-4 mb-2 border-bottom">
  <h2><%= fa_icon 'child', class: 'text-primary' %> 
    Ajouter un enfant au compte 
    '<%= @enfant.compte.nom %>'
  </h2>
</div>
<br>

<%= render 'form', enfant: @enfant %>

app/views/enfants/show.html.erb
<div class="card my-3">
  <div class="card-header">
    <h2>
      <%= fa_icon 'child', class: 'text-primary' %>
      <%= @enfant.prénom %>
      <%= @enfant.nom %>
    </h2>
  </div>

  <div class="card-body">
    <div class="row">
      <div class="col">
        <p>
          <strong>Compte :</strong>
          <%= link_to @enfant.compte.nom, @enfant.compte %>
        </p>

        <p>
          <strong>Classe :</strong>
          <%= @enfant.classroom.nom %>
        </p>

        <p>
          <strong>Badge :</strong>
          <%= @enfant.badge %>
        </p>
      </div>

      <div class="col">
        <p>
          <strong>Date naissance :</strong>
          <%= l(@enfant.date_naissance) if @enfant.date_naissance %>
        </p>

        <p class="alert <%= 'alert-info' unless @enfant.mémo.blank? %>" >
          <%= @enfant.mémo %>
        </p>
      </div>

      <div class="col">
        <p>
          <strong>Menu 'Sans porc' ? :</strong>
          <%= "OUI" if @enfant.menu_sp %>
        </p>

        <p class="alert <%= 'alert-warning' if @enfant.menu_all %>" >
          <strong>Allergie ? :</strong>
          <%= "OUI" if @enfant.menu_all %>
          <%= "=> #{ @enfant.allergenes }" if @enfant.menu_all %>
        </p>
      </div>

    </div>

    <div class="d-flex justify-content-between">
      <% if policy(@enfant).edit? %>
        <%= link_to edit_enfant_path(@enfant), class: "btn btn-outline-primary" do %>
          <%= fa_icon 'edit', text: ' Éditer' %> 
        <% end %>
      <% end %>

      <% if policy(@enfant).destroy? %>
        <%= button_to @enfant, method: :delete, 'data-turbo-confirm': 'Attention ! Les réservations, absences et prestations de cet enfant vont être détruites !! Êtes-vous bien certain.e de vouloir faire ça ?', class: 'btn btn-outline-danger' do %>
          <%= fa_icon 'trash-alt' %>
        <% end %>
      <% end %>
    </div>
  

    <div class="card mt-3">
      <div class="card-body">
        <h4><%= fa_icon 'calendar-alt', class: 'text-warning' %> Réservations</h4>
        <br>

        <div class="table-responsive">
          <table class="table table-bordered table-hover table-sm">
            <thead>
              <tr>
                <th>Prestation</th>
                <th>Début</th>
                <th>Fin</th>
                <th>Etat</th>
                <th>Lun</th>
                <th>Mar</th>
                <th>Mer</th>
                <th>Jeu</th>
                <th>Ven</th>
                <th>Sam</th>
                <th>Dim</th>
                <th>Matin</th>
                <th>Midi</th>
                <th>Soir</th>
                <th>HPS?</th>
              </tr>
            </thead>

            <% @enfant.reservations.actives.each do |reservation| %>
              <tr>
                <td><%= reservation.prestation_type.nom %>
                <td><%= l reservation.début %></td>
                <td><%= l reservation.fin %></td>

                <td><span class="badge <%= reservation.style %>"><%= reservation.workflow_state.humanize %></span></td>

                <td class="text-center"><%= number_with_precision(reservation.lundi, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.lundi > 0 %></td>
                <td class="text-center"><%= number_with_precision(reservation.mardi, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.mardi > 0 %></td>
                <td class="text-center"><%= number_with_precision(reservation.mercredi, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.mercredi > 0 %></td>
                <td class="text-center"><%= number_with_precision(reservation.jeudi, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.jeudi > 0 %></td>
                <td class="text-center"><%= number_with_precision(reservation.vendredi, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.vendredi > 0 %></td>
                <td class="text-center"><%= number_with_precision(reservation.samedi, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.samedi > 0 %></td>
                <td class="text-center"><%= number_with_precision(reservation.dimanche, locale: :fr, precision: 2, significant: true, strip_insignificant_zeros: true) if reservation.dimanche > 0 %></td>

                <td class="text-center"><%= fa_icon 'check' if reservation.matin %></i></td>
                <td class="text-center"><%= fa_icon 'check' if reservation.midi  %></i></td>
                <td class="text-center"><%= fa_icon 'check' if reservation.soir  %></i></td>

                <td class="text-center"><%= fa_icon 'umbrella-beach' if reservation.hors_période_scolaire %></i></td>
              </tr>
            <% end %>
          </table>
        </div>

        <% if policy(@enfant).edit? %>
          <%= link_to edit_enfant_path(@enfant), class: "btn btn-outline-primary" do %>
            <%= fa_icon 'edit', text: ' Éditer les réservations' %> 
          <% end %>
        <% end %>
      </div>
    </div>


    <div class="card">
      <div class="card-body">
        <h4><%= fa_icon 'calendar-times', class: 'text-danger' %> Absences</h4>
        <br>

        <div class="table-responsive">
          <table class="table table-bordered table-hover table-sm">
            <thead>
              <tr>
                <th>Début</th>
                <th>Fin</th>
                <th>Matin</th>
                <th>Midi</th>
                <th>Soir</th>
              </tr>
            </thead>

            <% @absences.each do |absence| %>
              <tr>
                <td><%= l absence.début %></td>
                <td><%= l absence.fin %></td>
                <td class="text-center"><%= fa_icon 'check' if absence.matin %></i></td>
                <td class="text-center"><%= fa_icon 'check' if absence.midi  %></i></td>
                <td class="text-center"><%= fa_icon 'check' if absence.soir  %></i></td>
              </tr>
            <% end %>
          </table>
        </div>

        <% if policy(Absence).new? %>
          <%= link_to new_absence_path(enfant_id: @enfant), class: 'btn btn-outline-primary', data: {'bs-toggle': "modal", 'bs-target': "#myModal" } do %>
            <%= fa_icon 'plus-circle' %> Ajouter une absence
          <% end %>
        <% end %>
        |
        <% if params[:archives] == 'yes' %>
          <%= link_to 'Afficher toutes les absences en cours (non-archivées)', url_for(params.permit.merge(archives: 'no')) %> 
        <% else %>
          <%= link_to 'Afficher les absences archivées', url_for(params.permit.merge(archives: 'yes')) %> 
        <% end %>

      </div>
    </div>

    <!-- The Modal -->
    <div class="modal fade" id="myModal">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Nouvelle Absence</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
            <%= render 'absences/modal_form', absence: Absence.new(enfant_id: @enfant.id) %>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <h4><%= fa_icon 'utensils', class: 'text-secondary' %> Prestations à facturer</h4>
        <br>

        <div class="table-responsive">
          <table class="table table-bordered table-hover table-sm">
            <thead>
              <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Qté</th>
              </tr>
            </thead>

            <% @enfant.prestations.à_facturer.order(:date).each do |prestation| %>
              <tr>
                <td><%= l prestation.date %></td>
                <td><%= prestation.prestation_type.nom %></td>
                <td><%= prestation.qté %></td>
              </tr>
            <% end %>
          </table>
        </div>

        <% if policy(Prestation).new? %>
          <%= link_to new_prestation_path(enfant_id: @enfant), class: 'btn btn-outline-primary', data: {'bs-toggle': "modal", 'bs-target': "#myModalPrestation" } do %>
            <%= fa_icon 'plus-circle' %> Ajouter une prestation
          <% end %>
        <% end %>

      </div>
    </div>

    <!-- The Modal -->
    <div class="modal fade shadow-lg" id="myModalPrestation">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Nouvelle Prestation</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
            <%= render 'prestations/modal_form', prestation: Prestation.new(enfant_id: @enfant.id) %>
          </div>
        </div>
      </div>
    </div>

    <br>

  </div>

</div>